# Generated by Django 2.0.4 on 2018-04-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('modified', models.DateTimeField(verbose_name='date modified')),
                ('responses', models.IntegerField(default=0)),
            ],
        ),
    ]
