# Generated by Django 2.0.4 on 2018-04-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180423_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Survey'),
        ),
    ]
