# Generated by Django 2.0.4 on 2018-04-24 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_surveyanswer_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='Surveytitle',
        ),
    ]
